compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 8
mixed_precision: bf16
use_cpu: false


# compute_environment: LOCAL_MACHINE
# distributed_type: NO
# num_processes: 1
# mixed_precision: bf16
# use_cpu: false
